### ISSUE TITLE
Guide request

### ISSUE THREAD

**Issue by RashiqAzhan** [mqj0712/plugin-sg-valid#1]
Detailed step-by-step usage guide?

**Comment by mqj0712** [comment]
there is no standalone guide for this plugin, it depends on framework [ja-netfilter](https://gitee.com/ja-netfilter/ja-netfilter), please refer that project for details.

**Comment by RashiqAzhan** [comment]
> for user:
download the jar file of the plugin
    put it in the subdirectory called plugins where the ja-netfilter.jar file is located
    enjoy the new capabilities brought by the plugin
    if the file suffix is .disabled.jar, the plugin will be disabled

   
I followed these steps.
I've also created the `sgvalid.conf` file with the vesion 1.1 regex method in it only.
Should I open an issue on the linked repo?

**Comment by mqj0712** [comment]
can you share the content of the vmoptions file you used, and screenshot of files list in your plugin / config folder ( better with full path in your file explorer)

**Comment by RashiqAzhan** [comment]
Thank you for taking a look.

# vmoptions
```vmoptions
-javaagent:/home/user/Documents/Jetbrain/smartgit/ja-netfilter/ja-netfilter.jar
--add-opens=java.base/jdk.internal.org.objectweb.asm=ALL-UNNAMED
--add-opens=java.base/jdk.internal.org.objectweb.asm.tree=ALL-UNNAMED
```

I"ve tried it this way as well.
```vmoptions
-javaagent:/home/user/Documents/Jetbrain/smartgit/ja-netfilter/ja-netfilter.jar
```

The same was tried for the vmoptions in `/home/user/.config/smartgit/`.

### vmoptions location
```vmoptions
/opt/smartgit/bin
❯ tree -fi
.
./add-menuitem.sh
./remove-menuitem.sh
./smartgit-128.png
./smartgit-256.png
./smartgit-32.png
./smartgit-48.png
./smartgit-64.png
./smartgit.sh
./smartgit.svg
./smartgit.vmoptions
```

# plugin
![image](https://github.com/mqj0712/plugin-sg-valid/assets/7370540/3ad6f77e-7042-4333-b4aa-5a1aa02321b8)

```
~/Documents/Jetbrain/smartgit/ja-netfilter/plugins
❯ tree -fi
.
./dns.jar
./hideme.jar
./native.jar
./power.jar
./sgvalid.jar
./url.jar
```

# config
![image](https://github.com/mqj0712/plugin-sg-valid/assets/7370540/c306fc68-04cc-4a9b-9a99-0058ceff0d17)

```
~/Documents/Jetbrain/smartgit/ja-netfilter/config
❯ tree -fi
.
./dns.conf
./native.conf
./power.conf
./sgvalid.conf
./url.conf
```

**Comment by mqj0712** [comment]
looks like the vmoption you show is for a jetbrains product, i don't think you are looking at the right place for your problem, maybe you should check out this site [https://3.jetbra.in/](https://3.jetbra.in/)

**Comment by RashiqAzhan** [comment]
I'm so sorry for the oversight. I've updated the post with the relevant info. I've grabbed the latest release from [here](https://gitee.com/ja-netfilter/ja-netfilter/releases/tag/2022.2.0). The problem persists.

**Comment by mqj0712** [comment]
looks like the vmoption (with the add-opens)  you tried is correct.
1. what's the version of smartgit you are trying to use?
2. if you have tried any license file? if not , you can find one from [here]([OneDrive(download link)](https://1drv.ms/u/s!Atf-z4aXHKwch1XvqOVLz78nE8zD?e=ImgItu))

if it is still not working, can you check the smartgit log file under ~/.config/smargit/<version>/logs, maybe you can find some clues, or you can attache it here for further investigation.

**Comment by RashiqAzhan** [comment]
Currently on version 23.1.3 #20195.

The license file is working.

Adding the smartgit agent jar file in the vmoptions (as suggested in the readme) prevented the software from even opening. I guess this plugin is taking over on behalf of that?

Thank you so much for your patience and assistance regarding the matter. You man close this issue at your convenience.
